## ALL GENERATED BY CHAT GPT
import sys

def main():
    if len(sys.argv) != 2:
        print("Usage: python analyze_binary_lines.py <filename>")
        sys.exit(1)

    filename = sys.argv[1]
    count_0 = 0
    count_1 = 0
    total = 0

    try:
        with open(filename, 'r') as file:
            for line in file:
                line = line.strip()
                if line == '0':
                    count_0 += 1
                    total += 1
                elif line == '1':
                    count_1 += 1
                    total += 1
               ## else:
                    ##print(f"Warning: Ignoring invalid line '{line}'")

        if total == 0:
            print("No valid 0/1 lines found.")
            return

        percent_0 = (count_0 / total) * 100
        percent_1 = (count_1 / total) * 100

        print(f"Total valid entries: {total}")
        print(f"0s: {count_0} ({percent_0:.2f}%)")
        print(f"1s: {count_1} ({percent_1:.2f}%)")

    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        sys.exit(1)

if __name__ == "__main__":
    main()

